name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v2
        with: 
          node-version: ${{ matrix.node-version }}
      - run: |
          npm i

